### ISSUE TITLE
Add progress bar for downloading

### ISSUE THREAD

**Issue by abcdesteve** [chenxiaolong/RSAF#101]
This is basically the same as #87. Please add progress bar for downloading as well. You can't count on the progress shown by any other file managers, for they always stay at a speed of 16kb/s and suddenly jump to over 20mb/s.

Thanks a lot.

**Comment by chenxiaolong** [comment]
Sorry, I don't plan on doing this for two reasons:

* Apps can perform random reads instead of sequential reads and a progress bar would not make sense here. There's no good way to detect how the client app is going to access the file.
* RSAF will see the exact same progress as the client app. Any buffering that happens (if any) is done inside rclone and there's no visibility into that.
