### ISSUE TITLE
Provide a way lock remote access with biometrics

### ISSUE THREAD

**Issue by ruby0b** [chenxiaolong/RSAF#106]
Hi, thank you for your work on this, I love being able to seamlessly use rclone on mobile.

I was wondering if there could be a way to lock access to a remote using biometrics, similar to how many sensitive apps have the ability to be locked?
It would then be re-locked automatically after some time.

I'm unsure about the details because I have no idea if and how the storage access framework could support this.

**Comment by chenxiaolong** [comment]
Glad you like RSAF!

This is sadly not possible with the storage access framework. The best you can do is manually disable the `Allow external app access` option when you want to "lock" a remote. However, this has annoying side effects: any app that was previously granted access to specific files/folders on that remote will have that access revoked, even after `Allow external app access` is reenabled. I've seen several apps handle that poorly and end up crashing.

**Comment by ruby0b** [comment]
Ah, that's too bad.
I was looking at this example repo and the screenshots seemed to suggest that there would be a way to not show the cloud service to other apps if it is currently not available.
Could this somehow be used to "lock" access until you open RSAF and "log back in"?

![image](https://github.com/user-attachments/assets/1ce1e6d5-97c4-4488-8835-2613506b8efe)

Different idea: Couldn't you show a fake empty directory of files until RSAF is opened which then modifies it to be the correct list of files?
After all, cloud files could also just suddenly vanish in an instant and then be immediately reuploaded.

(Sorry if these ideas don't make sense, I'm not familiar with android dev)

**Comment by chenxiaolong** [comment]
> I was looking at this example repo and the screenshots seemed to suggest that there would be a way to not show the cloud service to other apps if it is currently not available.

Yep, this is how the `Allow external app access` option currently works. Turning that option off is equivalent to logging out of a cloud app. From Android's perspective, a SAF root gets removed from the system and all prior permissions to it are revoked.

> Different idea: Couldn't you show a fake empty directory of files until RSAF is opened which then modifies it to be the correct list of files?

Yes, I think this could work. I'll have to think about it more and see if this is feasible to implement.

What would be the expected behavior when the remote is locked? Maybe something like this? (This is a list of all SAF operations)

| SAF operation | Action when locked |
|-----------|--------------------|
| List all roots | No change here. Locked remotes must still be visible or else permissions get revoked. |
| List directory contents | Return empty list for the root of the remote and "not found" error for any subdirectory? |
| Query file/directory metadata | Return "not found" error |
| Query if file belongs in a directory | Return "not found" error |
| Open an existing file | Return "not found" error |
| Create a new file/directory | Return "not found" error |
| Delete a file/directory | Return "not found" error |
| Copy a file/directory | Return "not found" error |
| Move a file/directory | Return "not found" error |

If RSAF is (auto-)locked while an app is still reading/writing to some files, should the app continue to have access to those files until they are closed or should those read/write operations get interrupted?

**Comment by ruby0b** [comment]
Looks great, I guess one could even show a fake empty file named "REMOTE IS LOCKED" in root or something like that for better user feedback.

> If RSAF is (auto-)locked while an app is still reading/writing to some files, should the app continue to have access to those files until they are closed or should those read/write operations get interrupted?

Hm, giving access to a file for a potentially unlimited time frame seems like an obvious security issue even though it would probably not be relevant in practice.
I can see it being necessary for accessing large files like playing movies from remote storage though.
I guess this could just be a toggle sub-setting?

**Comment by chenxiaolong** [comment]
I think at least for the initial implementation, I'll leave out the ability to interrupt operations. I'd rather try and keep the promise simple: new operations are blocked while the app is locked, but ongoing operations are allowed to complete.

There are two things I want to avoid:

* Inconsistency between operations. Reads/writes on open files can be easily interrupted, but file copies/moves cannot (rclone limitation).
* Causing file corruption because writes were interrupted for an open file.

**Comment by chenxiaolong** [comment]
I've implemented this in #110 and the ability to customize the lock timeout in #109. Both of these will be included in version 2.4.

I ended up making the "list directory contents" operation also return a file not found error so that all security restrictions are enforced in a single function that's used everywhere. It makes it a bit easier to verify that the logic is correct. If this is confusing or annoying UI-wise, I can change it later. This is what Android's system file manager shows while the app is locked: [Screenshot_20241216-224028](https://github.com/user-attachments/assets/aede6692-c784-4de7-a7b6-a4489456d68f)
