### ISSUE TITLE
Accessing virtual drive from within internal storage

### ISSUE THREAD

**Issue by seanstardev** [chenxiaolong/RSAF#43]
Hello. 

In my experience with RSAF, it is only possible to show a virtual drive as being adjacent to other physical root drives. Ie one can access the internal storage, the sd card, and any virtual drives mapped through rclone + RSAF and they all appear at the same 'top' level.

My question is - would it be possible for RSAF to spoof a drive being connected from within the internal storage or sd card file structure? I ask because RetroArch fails to see the mapped drives I set up. Nonetheless - most file browsing apps can see the mapped drives, so this is potentially a niche problem I am reporting.

I want to end by saying 2 things: your application is brilliant. I have some idea of the amount of work that must have gone into it. There is nothing trivial about what you have accomplished. Magnificent work. Take a bow!

Secondly - I'm so sorry about Meow-Meow. I just lost my 20 year old cat and, suffice to say, my heart is without on that one x

**Comment by chenxiaolong** [comment]
Thank you for the kind words! Sorry to hear about your cat as well.

Sounds like you're looking for something similar to FUSE mount points on Linux. Unfortunately, Android's SAF mechanism does not have this ability. Apps can only expose files in new top-level "roots" as they call it. In the same way that RSAF provides remote roots, there's an internal Android component called `ExternalStorageProvider` that provides the internal storage, SD card, and USB drive roots. An app cannot mess with another app's root in any way.

I took a look at RetroArch and it seems like it currently does not support accessing files through SAF. It only knows how to access local files on the internal storage. I don't blame them--SAF behaves quite differently from what other operating systems do. It can be difficult to add support for Android's special way of doing things to a cross-platform app.

I did find this RetroArch bug report for adding SAF support: https://github.com/libretro/RetroArch/issues/12181. The context of that is for SD card support, but once they support SAF, accessing RSAF files would automatically work.

---

(With root access, it might actually be possible to do what you want, but instead of using RSAF, you'd have to manually run the `rclone mount <remote> /sdcard/SomeFolder` command as root inside Termux. I haven't personally tried this, but it should be theoretically possible.)

**Comment by seanstardev** [comment]
> Thank you for the kind words! Sorry to hear about your cat as well.
> 
> Sounds like you're looking for something similar to FUSE mount points on Linux. Unfortunately, Android's SAF mechanism does not have this ability. Apps can only expose files in new top-level "roots" as they call it. In the same way that RSAF provides remote roots, there's an internal Android component called `ExternalStorageProvider` that provides the internal storage, SD card, and USB drive roots. An app cannot mess with another app's root in any way.
> 
> I took a look at RetroArch and it seems like it currently does not support accessing files through SAF. It only knows how to access local files on the internal storage. I don't blame them--SAF behaves quite differently from what other operating systems do. It can be difficult to add support for Android's special way of doing things to a cross-platform app.
> 
> I did find this RetroArch bug report for adding SAF support: [libretro/RetroArch#12181](https://github.com/libretro/RetroArch/issues/12181). The context of that is for SD card support, but once they support SAF, accessing RSAF files would automatically work.
> 
> (With root access, it might actually be possible to do what you want, but instead of using RSAF, you'd have to manually run the `rclone mount <remote> /sdcard/SomeFolder` command as root inside Termux. I haven't personally tried this, but it should be theoretically possible.)

It is rather difficult for me to articulate how grateful I am for this considered and in-depth response. It is so kind of you to look at my specific use case and give such an articulate answer.

I am humbled! I will investigate what is necessary to mount drives through 'rclone mount' and potentially still utilise your fantastic app.

My hope is to put a tutorial together for the emulation community on how to create aliases to their NAS drives, and promote your great work at every turn. I will also talk to the RetroArch guys and see what their take is. You have been superb. Thank you so, so much :)

**Comment by chenxiaolong** [comment]
No problem at all! Happy to help :)
