### ISSUE TITLE
Support for armv7

### ISSUE THREAD

**Issue by DarremMolko** [chenxiaolong/RSAF#6]
Hi. First than nothing congratulations for your wonderful app, I once though an app like this would be a game changer. I'd really love to check this app out but I have a low end device with android 10 and it's armv7. I hope you consider supporting this architecture in the future. 

PS: Does this app needs root? 

Best wishes.

**Comment by chenxiaolong** [comment]
Yep, sure thing. I actually built apks for every architecture, but I didn't upload them because I misunderstood Github's size limit for uploads.

I've now uploaded the `armeabi-v7a`, `x86`, and `x86_64` apks for every version.

> PS: Does this app needs root?

Nope, no root needed :) It doesn't require any invasive Android permissions either ([details](https://github.com/chenxiaolong/RSAF#permissions)).
