### ISSUE TITLE
不能多并发

### ISSUE THREAD

**Issue by kylinloong** [chenxiaolong/RSAF#72]
一次只能往里面复制一个文件？同时往里面复制多个件就会出错。而且要等第一个复制完成后才能再往里面复制第二个。而且不能修改文件名。使用webdav协议。

**Comment by chenxiaolong** [comment]
Unfortunately, I don't think this is fixable due to Android's limitations.

The Storage Access Framework is multithreaded, but only for requests from different apps. Requests from the same app (eg. a file manager) are processed sequentially.

---

You will probably need to use a different app that does not integrate with SAF.
