### ISSUE TITLE
Disable cache for large files

### ISSUE THREAD

**Issue by abcdesteve** [chenxiaolong/RSAF#79]
When uploading large files(e.g. videos>1G), is it possible to disable cache? Just read from the dir provided by the app and don't copy it to RSAF private dir. This will help reduce disk write and extremely useful when the device don't have enough space for cache

**Comment by chenxiaolong** [comment]
This is currently not possible.

I may add an option for it in the future, but it would have the same limitations as rclone when doing streaming writes. Files would have to be written sequentially (no random writes) and retries would not be supported in case of network issues.

**Comment by abcdesteve** [comment]
Currently RSAF would continue to upload when network is back, so I don't really understand why retries would be unavailable.

**Comment by abcdesteve** [comment]
BTW I'm quite curious if RSAF could show the approximate progress bar for upload and download in the notification, since large files currently will be cached first and there's no way to tell how much it had been uploaded.

Also it would be nice to see the upload speed and how much time left to finish the task. If it's technically possible, then please add a pause action button as well.

I know I'm requesting for too much, so just take them as an inspiration for  new functions.

**Comment by chenxiaolong** [comment]
> Currently RSAF would continue to upload when network is back, so I don't really understand why retries would be unavailable.

This is only possible when caching is enabled. With caching disabled, retrying is not possible. This is an rclone limitation: https://rclone.org/commands/rclone_mount/#vfs-cache-mode-off

rclone likely has this limitation because most backends don't actually support resuming uploads. "Retrying" is actually reuploading from scratch. Without the cached file, there's nowhere it can reread the data from. (RSAF cannot ask the client app to recreate the file either--the Android API does not support this.)

---

Regarding the upload progress, I'm unfortunately very limited by rclone here. There's no way to monitor anything about that process or control how it behaves besides turning it on or off completely. I _might_ be able to do something hacky to show the approximate progress, but pause/resume is definitely not possible.

**Comment by chenxiaolong** [comment]
I've implement support for disabling caching in #86 (equivalent to rclone's `--vfs-cache-mode none` option). It'll be included in the next release of RSAF.

I'm planning to take a look at the upload notification soon to see if I can implement some hacky workaround to show the progress.

**Comment by chenxiaolong** [comment]
The upload progress notification (for remotes with VFS caching enabled) has been updated to show the progress in #87. This will be included in the next version of RSAF as well.

The notification shows the size uploaded so far and the total size to upload. Given how hacky this is, I'd prefer not to try and compute the speed and complicate it further.
