### ISSUE TITLE
Password input could be improved

### ISSUE THREAD

**Issue by SigmaBonder** [chenxiaolong/RSAF#8]
Currently, when inputting password, there is no option to preview the contents of the masked field, which is problematic for the users as they have to ensure that they get it right in one go. However, when re-configuring a previously added remote, the password is visible in the prompt above, which is not ideal either* (I think it should just stay in the masked field with a possibility to reveal it).
<details><summary>Screenshot</summary>
<img alt="password input prompt" src="https://github.com/chenxiaolong/RSAF/assets/116167153/c0447c61-278c-4513-a404-d58456781ffe"/>
</details> 
*Please note #7 — I assume that currently RSAF just shows the contents of the config file, which won't be right if the fix for this issue is too shallow.

**Comment by chenxiaolong** [comment]
This should be fixed by #8. The password box now has the normal show password icon and the `Use current value`/`Use default value` switch has been replaced by a reset button. When editing an existing remote, the password will be properly displayed unobscured.

[Screenshot_20230620-003546](https://github.com/chenxiaolong/RSAF/assets/646253/6e82d1bb-2793-45ea-80f8-e9e9b545c051)
